# Comms
# Antenna
# get_Available
# get_GroundStations
# Antenna_get_Part
# Antenna_get_HasConnection
# Antenna_get_Target
# Antenna_set_Target
# Antenna_get_TargetBody
# Antenna_set_TargetBody
# Antenna_get_TargetGroundStation
# Antenna_set_TargetGroundStation
# Antenna_get_TargetVessel
# Antenna_set_TargetVessel
# Comms_SignalDelayToVessel
# Comms_get_Vessel
# Comms_get_HasLocalControl
# Comms_get_HasFlightComputer
# Comms_get_HasConnection
# Comms_get_HasConnectionToGroundStation
# Comms_get_SignalDelay
# Comms_get_SignalDelayToGroundStation
# Comms_get_Antennas
