# AddCanvas
# Message
# Clear
# get_StockCanvas
# Button_Remove
# Button_get_RectTransform
# Button_get_Text
# Button_get_Clicked
# Button_set_Clicked
# Button_get_Visible
# Button_set_Visible
# Canvas_AddPanel
# Canvas_AddText
# Canvas_AddInputField
# Canvas_AddButton
# Canvas_Remove
# Canvas_get_RectTransform
# Canvas_get_Visible
# Canvas_set_Visible
# InputField_Remove
# InputField_get_RectTransform
# InputField_get_Value
# InputField_set_Value
# InputField_get_Text
# InputField_get_Changed
# InputField_set_Changed
# InputField_get_Visible
# InputField_set_Visible
# Panel_AddPanel
# Panel_AddText
# Panel_AddInputField
# Panel_AddButton
# Panel_Remove
# Panel_get_RectTransform
# Panel_get_Visible
# Panel_set_Visible
# RectTransform_get_Position
# RectTransform_set_Position
# RectTransform_get_LocalPosition
# RectTransform_set_LocalPosition
# RectTransform_get_Size
# RectTransform_set_Size
# RectTransform_get_UpperRight
# RectTransform_set_UpperRight
# RectTransform_get_LowerLeft
# RectTransform_set_LowerLeft
# RectTransform_set_Anchor
# RectTransform_get_AnchorMax
# RectTransform_set_AnchorMax
# RectTransform_get_AnchorMin
# RectTransform_set_AnchorMin
# RectTransform_get_Pivot
# RectTransform_set_Pivot
# RectTransform_get_Rotation
# RectTransform_set_Rotation
# RectTransform_get_Scale
# RectTransform_set_Scale
# Text_Remove
# Text_get_RectTransform
# Text_get_AvailableFonts
# Text_get_Content
# Text_set_Content
# Text_get_Font
# Text_set_Font
# Text_get_Size
# Text_set_Size
# Text_get_Style
# Text_set_Style
# Text_get_Alignment
# Text_set_Alignment
# Text_get_LineSpacing
# Text_set_LineSpacing
# Text_get_Color
# Text_set_Color
# Text_get_Visible
# Text_set_Visible
